### ISSUE TITLE
Issue on create hash "$this->passhash->hash($_POST['UsrPassword']);"

### ISSUE THREAD

**Issue by prashantidealittechno** [dwightwatson/codeigniter-bcrypt#6]
A PHP Error was encountered

Severity: Warning

Message: is_readable(): open_basedir restriction in effect. File(/dev/urandom) is not within the allowed path(s):  (/var/www/web:/var/www/private:/var/www/web1/tmp:/var/www/web:/srv/www/web:/usr/share/php5:/usr/share/php:/tmp:/usr/share/phpmyadmin:/etc/phpmyadmin:/var/lib/phpmyadmin)

Filename: libraries/Bcrypt.php

Line Number: 88

Can you help me out how can i fix this error??

**Comment by dwightwatson** [comment]
Looks like this is an issue with your PHP configuration. Did you even try Googling the error? The first result [shows a solution when using Apache](https://stackoverflow.com/questions/1846882/open-basedir-restriction-in-effect-file-is-not-within-the-allowed-paths).

If you're using a version of PHP above 5.5, I'd highly recommend that you use the [built in `password_hash` function](https://secure.php.net/manual/en/function.password-hash.php) that is now a part of the language.
