### ISSUE TITLE
Why to use the no of function? are they same?

### ISSUE THREAD

**Issue by prashantidealittechno** [dwightwatson/codeigniter-bcrypt#7]
I try to save the password decrypt with this '''hash_password''' of below class( passHash.php file) in codeigniter and check with this bcrypt library that is given and it return me true that password match.

i also save passwrod with bcrypt function and check password with below funciton  '''check_password'''( passHash.php file) and it again return me true. are they same??

is password secure with this bcrypt lib??

Pass hash 
'''
class PassHash {

    // blowfish
    private static $algo = '$2a';
    // cost parameter
    private static $cost = '$10';

    // mainly for internal use
    public static function unique_salt() {
        return substr(sha1(mt_rand()), 0, 22);
    }

    // this will be used to generate a hash
    public static function hash_password($password) {

        return crypt($password, self::$algo .
                self::$cost .
                '$' . self::unique_salt());
    }

    // this will be used to compare a password against a hash
    public static function check_password($password, $hash) {
        $full_salt = substr($hash, 0, 29);
        $new_hash = crypt($password, $full_salt);
        return ($hash == $new_hash);
    }

}
'''
which one is good and what i have to use,

**Comment by dwightwatson** [comment]
I'm not a cryptologist, so I'm not qualified to assess the security of the code you've pasted. This library is simply an implementation of Bcrypt called PHPPass packaged into a CodeIgniter library. Like I said on the previous issue you should seriously look at the `password_hash` function provided by PHP 5.5 and if you're on an older version look at the [`password_compat` library](https://github.com/ircmaxell/password_compat) which provides future compatibility.

I would highly suggest you look at those options over this very library and the code you have pasted.
