### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by EnriqueV** [dwightwatson/codeigniter-bcrypt#8]
Hi I am developing a php web service is for mobile applications, but without using CodeIgniter is a simple PHP script, and I have a website and I use CodeIgniter library bcrypt login and password registration. but for my mobile app use this: http://www.openwall.com/articles/PHP-Users-Passwords my problem is that the password sent by my mobile application is incompatible to access my website made in codeigniter and encrypting password with bcrypt, you can use this library in php without codeigniter? thanks and I hope you can help

**Comment by dwightwatson** [comment]
I'm not really sure what you're asking there. This library was built to be used with CodeIgniter, but it can also be used standalone, it's just a simple class. That said, this library is no longer maintained and it's recommended that you use the [`password_hash`](https://secure.php.net/manual/en/function.password-hash.php) functionality that is now provided by PHP itself to hash passwords.
