### ISSUE TITLE
check_password function returns false always 

### ISSUE THREAD

**Issue by sibivenkataraju** [dwightwatson/codeigniter-bcrypt#9]
When i enter correct password for login ,$this->bcrypt->check_password($password,$storedpasswoord)  return false always
i have tried many time but no change,also tried to create hash_password its return different hashes each time.

please help

**Comment by dwightwatson** [comment]
Hey, sorry - I no longer work with CodeIgniter and the library this was built on is no longer supported. Please refer [to this comment for suggestions on how to better hash your passwords](https://github.com/dwightwatson/codeigniter-bcrypt/issues/8#issuecomment-166210811).
